language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - "pip install -r requirements-dev.txt"
  - "pip install codecov"
  - "python setup.py install"
before_script:
  - "flake8 sodapy/"
  - "flake8 tests/"
script:
  - coverage run --source sodapy -m pytest
  - coverage report

after_success:
    - codecov
